---Create Group Menu Table 
CREATE TABLE GROUP_MENU
(
  GROUP_MENU_ID NUMBER(10) NOT NULL, 
  GROUP_ID NUMBER(10) NOT NULL,
  MENU_ID NUMBER(10) NOT NULL,
  IS_ACTIVE VARCHAR2(1),
  PROGRAM_NAME VARCHAR2(100),
  CREATED_DATE DATE NOT NULL, 
  CREATED_BY VARCHAR2(100) NOT NULL, 
  UPDATED_DATE DATE, 
  UPDATED_BY VARCHAR2(100),
  
  CONSTRAINT pk_group_menu PRIMARY KEY (GROUP_MENU_ID),
  CONSTRAINT fk_group_id FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID),
  CONSTRAINT fk_menu_id FOREIGN KEY (MENU_ID) REFERENCES MENUS (MENU_ID)
);